# Generated by Django 5.0 on 2023-12-25 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('link_for_recording', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Кружки',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('patronymic', models.CharField(max_length=250)),
                ('bio', models.CharField(max_length=250)),
                ('about', models.TextField()),
                ('photo', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='MugsPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.BinaryField()),
                ('mug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mugs')),
            ],
        ),
        migrations.AddField(
            model_name='mugs',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
    ]
