# Generated by Django 5.0 on 2023-12-26 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mugsphotos_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('actual_event', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='mugs',
            options={'verbose_name': 'Кружок', 'verbose_name_plural': 'Кружки'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Педагог', 'verbose_name_plural': 'Педагоги'},
        ),
        migrations.AlterField(
            model_name='mugs',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mugs',
            name='link_for_recording',
            field=models.TextField(verbose_name='Ссылка для записи'),
        ),
        migrations.AlterField(
            model_name='mugs',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher', verbose_name='Педагог'),
        ),
        migrations.AlterField(
            model_name='mugs',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mugsphotos',
            name='mug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mugs', verbose_name='Кружок'),
        ),
        migrations.AlterField(
            model_name='mugsphotos',
            name='photo',
            field=models.CharField(max_length=250, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='about',
            field=models.TextField(verbose_name='О педагоге'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=models.CharField(max_length=250, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=250, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(max_length=250, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.CharField(max_length=250, verbose_name='Фото'),
        ),
    ]
