# Generated by Django 5.0 on 2023-12-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_actual_alter_mugs_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actual',
        ),
    ]
