# Generated by Django 5.0 on 2023-12-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('div', models.TextField()),
                ('script1', models.TextField()),
                ('script2', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Актуальные события',
            },
        ),
    ]
