# Generated by Django 5.0 on 2023-12-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_actualevents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualevents',
            old_name='script1',
            new_name='script',
        ),
        migrations.RemoveField(
            model_name='actualevents',
            name='script2',
        ),
    ]
