# Generated by Django 5.0 on 2023-12-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_script1_actualevents_script_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualevents',
            name='div',
        ),
        migrations.RemoveField(
            model_name='actualevents',
            name='script',
        ),
        migrations.AddField(
            model_name='actualevents',
            name='div_id',
            field=models.CharField(default='post_1', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actualevents',
            name='hash',
            field=models.CharField(default='Hash1', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actualevents',
            name='owner_id',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actualevents',
            name='post_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
