# Generated by Django 5.0 on 2023-12-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_actualevents_div_remove_actualevents_script_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActualEvents',
        ),
    ]
