# Generated by Django 5.0 on 2023-12-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_actualevents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActualEvents',
            new_name='Actual',
        ),
    ]
