# Generated by Django 5.0 on 2023-12-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_teacher_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.AddField(
            model_name='mugs',
            name='preview',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='mugsphotos',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Фото'),
        ),
    ]
