# Generated by Django 5.0 on 2024-01-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_events_mugs_preview_alter_mugsphotos_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('link', models.CharField(max_length=250, verbose_name='Ссылка на форму')),
            ],
            options={
                'verbose_name': 'Конкурсы',
                'verbose_name_plural': 'Конкурс',
            },
        ),
        migrations.CreateModel(
            name='Masterclasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('link', models.CharField(max_length=250, verbose_name='Ссылка на форму')),
            ],
            options={
                'verbose_name': 'Мастер-классы',
                'verbose_name_plural': 'Мастер-класс',
            },
        ),
    ]
