# Generated by Django 5.0 on 2024-01-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_contests_masterclasses'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='masterclasses',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Фото'),
        ),
    ]
