# Generated by Django 5.0 on 2024-01-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_contests_photo_masterclasses_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contests',
            options={'verbose_name': 'Конкурс', 'verbose_name_plural': 'Конкурсы'},
        ),
        migrations.AlterModelOptions(
            name='masterclasses',
            options={'verbose_name': 'Мастер-класс', 'verbose_name_plural': 'Мастер-классы'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(upload_to='media/', verbose_name='Фото'),
        ),
    ]
