# Generated by Django 5.0 on 2024-01-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_contests_options_alter_masterclasses_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='media/events')),
                ('is_event', models.BooleanField()),
                ('text', models.TextField(null=True)),
            ],
        ),
    ]
