# Generated by Django 5.0 on 2024-01-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'События'},
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
