# Generated by Django 5.0 on 2024-01-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_event_options_alter_event_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.TextField(default='Hello', verbose_name='Ссылка "подробнее"'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='media/events', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_event',
            field=models.BooleanField(verbose_name='Является событием'),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст, если является событием'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
