# Generated by Django 5.0 on 2024-01-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_event_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contests',
            options={'ordering': ['id'], 'verbose_name': 'Конкурс', 'verbose_name_plural': 'Конкурсы'},
        ),
        migrations.AlterModelOptions(
            name='masterclasses',
            options={'ordering': ['id'], 'verbose_name': 'Мастер-класс', 'verbose_name_plural': 'Мастер-классы'},
        ),
        migrations.AlterModelOptions(
            name='mugs',
            options={'ordering': ['id'], 'verbose_name': 'Кружок', 'verbose_name_plural': 'Кружки'},
        ),
        migrations.AlterModelOptions(
            name='mugsphotos',
            options={'verbose_name': 'Фото с кружков', 'verbose_name_plural': 'Фото с кружков'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['id'], 'verbose_name': 'Педагог', 'verbose_name_plural': 'Педагоги'},
        ),
        migrations.AddField(
            model_name='contests',
            name='regulation',
            field=models.FileField(default='Hello!', upload_to='media/regulation/', verbose_name='Положение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contests',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/contests/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='masterclasses',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/masterclasses/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='mugs',
            name='preview',
            field=models.ImageField(null=True, upload_to='media/mugs/preview', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='mugsphotos',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/mugs', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(upload_to='media/teachers', verbose_name='Фото'),
        ),
    ]
